trigger:
  branches:
    include:
      - main  # Or your target branch

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Checkout the code
  - checkout: self

  # Step 2: Create a new file
  - script: |
      echo "This file was created by Azure Pipelines!" > newfile.txt
      cat newfile.txt
    displayName: "Create new file"

  # Step 3: Configure Git
  - script: |
      git config user.email "build-agent@azuredevops.com"
      git config user.name "Azure DevOps Pipeline"
    displayName: "Configure Git"

  # Step 4: Commit and push
  - script: |
      git add newfile.txt
      git commit -m "Add new file via Azure Pipeline" || echo "Nothing to commit"
      git push origin HEAD:main
    displayName: "Commit and push file"
    env:
      GIT_AUTHORIZATION: $(System.AccessToken)
