name: Create Text File in GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  create-text-file:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create a new text file
      - name: Create a text file
        run: |
          echo "This is a new text file created by GitHub Actions!" > newfile.txt
          cat newfile.txt  # Optional: Check the file content

      # Step 3: Commit the new file
      - name: Commit and push the file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add newfile.txt
          git commit -m "Create new text file via GitHub Actions"
          git push origin main
