trigger:
  - none
pr: none
  

pool:
  name: 'az-weu-ubuntu-22.04-amd64-2cpu'

steps:
  - checkout: self
    submodules: true
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'

  - task: AzureKeyVault@2
    displayName: Azure Key Vault
    inputs:
      azureSubscription: '#####'
      KeyVaultName: '####'
      SecretsFilter: '*'
      RunAsPreJob: false  

  

  
  
